date: 2022-11-29 15:30:08
icon: "database.svg"
title: PostgreSQL & MySQL
description: Sql & NoSql
body: Quisque ut dolor gravida, placerat libero vel, euismod. Quis aute iure reprehenderit in voluptate velit esse. Curabitur blandit tempus ardua ridiculus sed magna.
