name: Deploy to EC2

on:
  pull_request:
    branches:
      - main  # Altere para a branch desejada

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18  # Use a versão de Node.js adequada
          
      - name: set private key permissions
        run: chmod 600 /home/ec2-user/.ssh/authorized_keys

      - name: Install dependencies
        run: npm install

      - name: Build React App
        run: npm run build

      - name: Copy files with SCP
        uses: appleboy/ssh-action@v1.0.0
        with:
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "build/"  # Caminho para os arquivos build
          target: "/var/www/html"  # Diretório no servidor EC2
